routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/impersonate', 'ImpersonateController@index');
    Route::post('/impersonate', 'ImpersonateController@start')->name('impersonate.start');
});

Route::delete('/admin/impersonate', 'Admin\ImpersonateController@destroy')->name('admin.impersonate.destroy');

Route::group(['middleware' => ['auth', 'subscription.active']], function () {
    Route::get('/dashboard', 'DashboardController@index');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('/login/twofactor', 'Auth\TwoFactorLoginController@index')->name('login.twofactor.index');
    Route::post('/login/twofactor', 'Auth\TwoFactorLoginController@verify')->name('login.twofactor.verify');
});

/**
 * Account
 */
Route::group(['prefix' => 'account', 'middleware' => ['auth'], 'as' => 'account.', 'namespace' => 'Account'], function () {
    Route::get('/', 'AccountController@index')->name('index');

    /**
     * Profile
     */
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::post('profile', 'ProfileController@store')->name('profile.store');

    /**
     * Password
     */
    Route::get('password', 'PasswordController@index')->name('password.index');
    Route::post('password', 'PasswordController@store')->name('password.store');

    /**
     * Password
     */
    Route::get('tokens', 'TokenController@index')->name('tokens.index');

    /**
     * Deactive
     */
    Route::get('deactivate', 'DeactivateController@index')->name('deactivate.index');
    Route::post('deactivate', 'DeactivateController@store')->name('deactivate.store');

    /**
     * Two factor
     */
    Route::group([], function () {
        Route::get('/twofactor', 'TwoFactorController@index')->name('twofactor.index');
        Route::post('/twofactor', 'TwoFactorController@store')->name('twofactor.store');
        Route::post('/twofactor/verify', 'TwoFactorController@verify')->name('twofactor.verify');
        Route::delete('/twofactor', 'TwoFactorController@destroy')->name('twofactor.destroy');
    });

    /**
     * Subscription
     */
    Route::group(['prefix' => 'subscription', 'namespace' => 'Subscription'], function () {
            /**
         * Cancel
         */
        Route::group(['middleware' => 'subscription.notcancelled'], function () {
            Route::get('/cancel', 'SubscriptionCancelController@index')->name('subscription.cancel.index');
            Route::post('/cancel', 'SubscriptionCancelController@store')->name('subscription.cancel.store');
        });

        /**
         * Resume
         */
        Route::group(['middleware' => 'subscription.cancelled'], function () {
            Route::get('/resume', 'SubscriptionResumeController@index')->name('subscription.resume.index');
            Route::post('/resume', 'SubscriptionResumeController@store')->name('subscription.resume.store');
        });

        /**
         * Swap
         */
        Route::group(['middleware' => 'subscription.notcancelled'], function () {
            Route::get('/swap', 'SubscriptionSwapController@index')->name('subscription.swap.index');
            Route::post('/swap', 'SubscriptionSwapController@store')->name('subscription.swap.store');
        });

        /**
         * Card
         */
        Route::group(['middleware' => 'subscription.customer'], function () {
            Route::get('/card', 'SubscriptionCardController@index')->name('subscription.card.index');
            Route::post('/card', 'SubscriptionCardController@store')->name('subscription.card.store');
        });
    

        /**
         * Team
         */
  
            Route::get('/team', 'SubscriptionTeamController@index')->name('subscription.team.index');
            Route::patch('/team', 'SubscriptionTeamController@update')->name('subscription.team.update');

            Route::post('/team/member', 'SubscriptionTeamMemberController@store')->name('subscription.team.member.store');
            Route::delete('/team/member/{user}', 'SubscriptionTeamMemberController@destroy')->name('subscription.team.member.destroy');
        
    });

});

/**
 * Account activation.
 */
Route::group(['prefix' => 'activation', 'as' => 'activation.', 'middleware' => ['guest']], function () {
    Route::get('/resend', 'Auth\ActivationResendController@index')->name('resend');
    Route::post('/resend', 'Auth\ActivationResendController@store')->name('resend.store');
    Route::get('/{confirmation_token}', 'Auth\ActivationController@activate')->name('activate');
});

/**
 * Subscription plans.
 */
Route::group(['prefix' => 'plans', 'as' => 'plans.'], function () {
    Route::get('/', 'Subscription\PlanController@index')->name('index');
    Route::get('/teams', 'Subscription\PlanTeamController@index')->name('teams.index');
});

/**
 * Subscription
 */
Route::group(['prefix' => 'subscription', 'as' => 'subscription.', 'middleware' =>['auth.register']], function () {
    Route::get('/', 'Subscription\SubscriptionController@index')->name('index');
    Route::post('/', 'Subscription\SubscriptionController@store')->name('store');
});

/**
 * Webhooks
 */

Route::post('/webhooks/stripe', 'Webhooks\StripeWebhookController@handleWebhook');

app/Http/Controllers/Account/Subscription/SubscriptionCancelController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionCancelController extends Controller
{
   
    public function index()
    {
        return view('account.subscription.cancel.index');
    }

      public function store(Request $request)
    {
        $request->user()->subscription('main')->cancel();

        return redirect()->route('account.index')->withSuccess('Your subscription has been cancelled.');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionCardController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionCardController extends Controller
{
    public function index()
    {
        return view('account.subscription.card.index');
    }

    public function store(Request $request)
    {
        $request->user()->updateCard($request->token);

        return redirect()->route('account.index')->withSuccess('Your card has been updated.');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionResumeController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionResumeController extends Controller
{
    public function index()
    {
        return view('account.subscription.resume.index');
    }

    public function store(Request $request)
    {
        $request->user()->subscription('main')->resume();

        return redirect()->route('account.index')->withSuccess('Your subscription has been resumed.');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionSwapController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\Subscription\SubscriptionSwapStoreRequest;

class SubscriptionSwapController extends Controller
{
    public function index()
    {
        $plans = Plan::except(auth()->user()->plan->id)->active()->get();

        return view('account.subscription.swap.index', compact('plans'));
    }

    public function store(SubscriptionSwapStoreRequest $request)
    {
        $user = $request->user();

        $plan = Plan::where('gateway_id', $request->plan)->first();

        if ($this->downgradesFromTeamPlan($user, $plan)) {
            $user->team->users()->detach();
        }

        $user->subscription('main')->swap($plan->gateway_id);

        return back()->withSuccess('Your subscription was changed.');
    }

    protected function downgradesFromTeamPlan(User $user, Plan $plan)
    {
        if ($user->plan->isForTeams() && $plan->isNotForTeams()) {
            return true;
        }

        return false;
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionTeamController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use App\Http\Controllers\Controller;
use App\Http\Requests\Account\SubscriptionTeamUpdateRequest;
use Illuminate\Http\Request;

class SubscriptionTeamController extends Controller
{
    public function index(Request $request)
    {
        $team = $request->user()->team;

        return view('account.subscription.team.index', compact('team'));
    }

    public function update(SubscriptionTeamUpdateRequest $request)
    {
        $request->user()->team()->update($request->only(['name']));

        return back()->withSuccess('Team name updated');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionTeamMemberController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use App\Http\Controllers\Controller;
use App\Http\Requests\Account\SubscriptionTeamMemberStoreRequest;
use App\Models\User;
use Illuminate\Http\Request;

class SubscriptionTeamMemberController extends Controller
{
    public function store(SubscriptionTeamMemberStoreRequest $request)
    {
        if ($this->teamLimitReached($request)) {
            return back()->withError('You have reached the team limit for your plan.');
        }
        
        $request->user()->team->users()->syncWithoutDetaching([
            User::where('email', $request->email)->first()->id
        ]);

        return back()->withSuccess('Team member added.');
    }

    public function destroy(User $user, Request $request)
    {
        $request->user()->team->users()->detach($user->id);

        return back()->withSuccess('Member has been removed.');
    }

    protected function teamLimitReached($request)
    {
        return $request->user()->team->users->count() === $request->user()->plan->teams_limit;
    }
}

app/Http/Controllers/Subscription/PlanController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Models\Plan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PlanController extends Controller
{
     public function index()
    {
   
       $plans = Plan::active()->forUsers()->get();

        return view('subscription.plans.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/PlanTeamController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use Illuminate\Http\Request;

class PlanTeamController extends Controller
{
    public function index()
    {
        $plans = Plan::active()->forTeams()->get();

        return view('subscription.plans.teams.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/SubscriptionController.php
<?php

namespace App\Http\Controllers\Subscription;

use Illuminate\Http\Request;
use App\Models\Plan;
use App\Http\Controllers\Controller;
use App\Http\Requests\Subscription\SubscriptionStoreRequest;

class SubscriptionController extends Controller
{
    public function index()
    {
        $plans = Plan::active()->get();

        return view('subscription.index', compact('plans'));
    }

    
    public function store(SubscriptionStoreRequest $request)
    {
        $subscription = $request->user()->newSubscription('main', $request->plan);

       
        if ($request->has('coupon')) {
            $subscription->withCoupon($request->coupon);
        }

        $subscription->create($request->token);

        return redirect('/')->withSuccess('Thanks for becoming a subscriber.');
    }

}

resources/views/subscription/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Subscription
                </div>
                <div class="panel-body">
                    <form action="{{ route('subscription.store') }}" method="POST" class="form-horizontal" id="payment-form">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('plan') ? ' has-error' : '' }}">
                            <label for="plan" class="col-md-4 control-label">Plan</label>

                            <div class="col-md-6">
                                <select name="plan" id="plan" class="form-control">
                                    @foreach ($plans as $plan)
                                        <option value="{{ $plan->gateway_id }}" {{ request('plan') === $plan->slug || old('plan') === $plan->gateway_id ? 'selected="selected"' : '' }}>{{ $plan->name }} (£{{ $plan->price }})</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('plan'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('plan') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('coupon') ? ' has-error' : '' }}">
                            <label for="coupon" class="col-md-4 control-label">Coupon code</label>

                            <div class="col-md-6">
                                <input type="text" name="coupon" id="coupon" class="form-control" value="{{ old('coupon') }}">

                                @if ($errors->has('coupon'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('coupon') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                              <button type="submit" class="btn btn-primary" id="pay">Pay</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://checkout.stripe.com/checkout.js"></script>
       <script>
        let handler = StripeCheckout.configure({
            key: '{{ config('services.stripe.key') }}',
            locale: 'auto',
            token: function (token) {
                let form = $('#payment-form')

                $('#pay').prop('disabled', true)

                $('<input>').attr({
                    type: 'hidden',
                    name: 'token',
                    value: token.id
                }).appendTo(form)

                form.submit();
            }
        })

        $('#pay').click(function (e) {
            handler.open({
                name: 'Codecourse Ltd.',
                description: 'Membership',
                currency: 'gbp',
                key: '{{ config('services.stripe.key') }}',
                email: '{{ auth()->user()->email }}'
            })

            e.preventDefault();
        })
    </script>
@endsection